# Generated by Django 5.2 on 2025-04-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('etiquetas', models.CharField(blank=True, max_length=255)),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('es_favorita', models.BooleanField(default=False)),
            ],
        ),
    ]
