# Generated by Django 5.2 on 2025-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='imagen_url',
            new_name='portada',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='calificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='etiquetas',
            field=models.CharField(max_length=255),
        ),
    ]
